version: "2"
services:
  app:
    extends:
      file: docker-compose.build.yml
      service: mvn
    container_name: JULA-Async-Connector
    ports:
      - "8080:8080"
    mem_limit: 500m
    mem_reservation: 450m
    command: spring-boot:run
    env_file: .env